<?php
/*define('hostname','50.62.209.117:3306');
define('dbuser','wdyogesh_gps');
define('dbpass','mEg85?9s');
define('dbname','wdyogesh_gps_bins');*/
define('hostname','localhost');
define('dbuser','vish_patrika');
define('dbpass','vish_patrika');
define('dbname','vish_patrika');
?>